[build]
command = "remix build && cp _app_redirects public/_redirects"
publish = "public"
functions = "functions/"

[dev]
command = "npm run dev"
targetPort = 3000

[[headers]]
for = "/build/*"

[[redirects]]
from = "*:8888/*"
to = "*:3000/*"
force = true

[headers.values]
# Set to 60 seconds as an example. You can also add cache headers via Remix. See the documentation on [headers](https://remix.run/docs/en/v1/route/headers) in Remix.
"Cache-Control" = "public, max-age=60, s-maxage=60"
